<?php

namespace DynamicCRUD\Installer;

class ConfigGenerator
{
    public function generate(array $config): string
    {
        $template = <<<'PHP'
<?php
/**
 * DynamicCRUD Configuration
 * Generated by installer on %timestamp%
 */

return [
    // Database Configuration
    'database' => [
        'driver' => '%driver%',
        'host' => '%host%',
        'database' => '%database%',
        'username' => '%username%',
        'password' => '%password%',
        'charset' => 'utf8mb4',
    ],

    // Site Configuration
    'site' => [
        'title' => '%site_title%',
        'url' => '%site_url%',
        'language' => '%language%',
    ],

    // Security
    'security' => [
        'secret_key' => '%secret_key%',
    ],

    // Paths
    'paths' => [
        'uploads' => __DIR__ . '/examples/uploads',
        'cache' => __DIR__ . '/cache',
        'templates' => __DIR__ . '/templates',
    ],
];

PHP;

        $replacements = [
            '%timestamp%' => date('Y-m-d H:i:s'),
            '%driver%' => $config['driver'] ?? 'mysql',
            '%host%' => $config['host'] ?? 'localhost',
            '%database%' => $config['database'] ?? '',
            '%username%' => $config['username'] ?? '',
            '%password%' => $config['password'] ?? '',
            '%site_title%' => $config['site_title'] ?? 'My Site',
            '%site_url%' => $config['site_url'] ?? '',
            '%language%' => $config['language'] ?? 'en',
            '%secret_key%' => $this->generateSecretKey(),
        ];

        return str_replace(array_keys($replacements), array_values($replacements), $template);
    }

    public function save(string $content, string $path = 'config.php'): array
    {
        try {
            $written = file_put_contents($path, $content);

            if ($written === false) {
                return [
                    'success' => false,
                    'error' => 'Failed to write config file',
                ];
            }

            return [
                'success' => true,
                'message' => 'Configuration file created successfully',
                'path' => $path,
                'bytes' => $written,
            ];
        } catch (\Exception $e) {
            return [
                'success' => false,
                'error' => $e->getMessage(),
            ];
        }
    }

    private function generateSecretKey(): string
    {
        return bin2hex(random_bytes(32));
    }
}
